kumuluzee:
  datasources:
    - jndi-name: jdbc/unir-citas-medicas-DS
      connection-url: jdbc:postgresql://173.249.51.238:5432/sch_citas_medicas
      username: postgres
      password: yeco2010
      max-pool-size: 20
  server:
    http:
      port: 8084
  discovery:
    consul:
      agent: http://173.249.51.238:8500
      hosts: http://173.249.51.238:8500
    ttl: 20
    ping-interval: 15
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://173.249.51.238:8500
      hosts: http://173.249.51.238:8500
  